<?xml version='1.1' encoding='UTF-8'?>
<flow-build plugin="workflow-job@1571.1580.v18e46842c125">
  <actions>
    <hudson.model.CauseAction>
      <causeBag class="linked-hash-map">
        <entry>
          <hudson.model.Cause_-UserIdCause>
            <userId>admin</userId>
          </hudson.model.Cause_-UserIdCause>
          <int>1</int>
        </entry>
      </causeBag>
    </hudson.model.CauseAction>
    <jenkins.metrics.impl.TimeInQueueAction plugin="metrics@4.2.37-494.v06f9a_939d33a_">
      <queuingDurationMillis>0</queuingDurationMillis>
      <blockedDurationMillis>0</blockedDurationMillis>
      <buildableDurationMillis>0</buildableDurationMillis>
      <waitingDurationMillis>0</waitingDurationMillis>
    </jenkins.metrics.impl.TimeInQueueAction>
    <org.jenkinsci.plugins.workflow.libs.LibrariesAction plugin="pipeline-groovy-lib@797.v90ea_a_9b_e45a_0">
      <libraries/>
    </org.jenkinsci.plugins.workflow.libs.LibrariesAction>
    <org.jenkinsci.plugins.pipeline.modeldefinition.actions.ExecutionModelAction plugin="pipeline-model-definition@2.2277.v00573e73ddf1">
      <stagesUUID>f707583c-aef0-4c59-92d0-b5511a5ffac7</stagesUUID>
      <pipelineDefs>
        <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTPipelineDef plugin="pipeline-model-api@2.2277.v00573e73ddf1">
          <stages>
            <stages>
              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
                <name>Environment</name>
                <branches>
                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                    <name>default</name>
                    <steps>
                      <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                        <name>bat</name>
                        <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTNamedArgumentList">
                          <arguments class="linked-hash-map">
                            <entry>
                              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                <key>script</key>
                              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                <value class="string">java -version</value>
                              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                            </entry>
                          </arguments>
                        </args>
                      </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                      <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                        <name>bat</name>
                        <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTNamedArgumentList">
                          <arguments class="linked-hash-map">
                            <entry>
                              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                <key>script</key>
                              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                <value class="string">mvn -version</value>
                              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                            </entry>
                          </arguments>
                        </args>
                      </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                    </steps>
                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                </branches>
              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
                <name>Build ParaBank</name>
                <branches>
                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                    <name>default</name>
                    <steps>
                      <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTTreeStep>
                        <name>dir</name>
                        <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTSingleArgument">
                          <value class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue$GStringValue">
                            <value class="string">${env.PROJECT_DIR}</value>
                          </value>
                        </args>
                        <children>
                          <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                            <name>bat</name>
                            <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTNamedArgumentList">
                              <arguments class="linked-hash-map">
                                <entry>
                                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                    <key>script</key>
                                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                    <value class="string">mvn -DskipTests clean package</value>
                                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                </entry>
                              </arguments>
                            </args>
                          </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                        </children>
                      </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTTreeStep>
                    </steps>
                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                </branches>
              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
                <name>Start ParaBank</name>
                <branches>
                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                    <name>default</name>
                    <steps>
                      <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTTreeStep>
                        <name>dir</name>
                        <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTSingleArgument">
                          <value class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue$GStringValue">
                            <value class="string">${env.PROJECT_DIR}</value>
                          </value>
                        </args>
                        <children>
                          <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                            <name>bat</name>
                            <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTNamedArgumentList">
                              <arguments class="linked-hash-map">
                                <entry>
                                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                    <key>script</key>
                                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                    <value class="string">
                        @echo off
                        set JENKINS_NODE_COOKIE=dontKillMe
                        set BUILD_ID=dontKillMe
                        if exist target\parabank-cargo.log del /q target\parabank-cargo.log
                        start &quot;parabank&quot; /B cmd /c mvn -DskipTests &quot;%CARGO_GOAL%:run&quot; ^&gt; target\parabank-cargo.log 2^&gt;^&amp;1
                    </value>
                                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                </entry>
                              </arguments>
                            </args>
                          </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                        </children>
                      </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTTreeStep>
                    </steps>
                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                </branches>
              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
                <name>Wait For ParaBank</name>
                <branches>
                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                    <name>default</name>
                    <steps>
                      <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTTreeStep>
                        <name>dir</name>
                        <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTSingleArgument">
                          <value class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue$GStringValue">
                            <value class="string">${env.PROJECT_DIR}</value>
                          </value>
                        </args>
                        <children>
                          <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                            <name>bat</name>
                            <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTNamedArgumentList">
                              <arguments class="linked-hash-map">
                                <entry>
                                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                    <key>script</key>
                                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                    <value class="string">
                        @echo off
                        for /L %%i in (1,1,40) do (
                            curl.exe --fail --silent &quot;%PARABANK_URL%&quot; | findstr /C:&quot;name=\&quot;username\&quot;&quot; &gt; nul
                            if not errorlevel 1 exit /b 0
                            echo ParaBank not ready yet, attempt %%i
                            ping 127.0.0.1 -n 4 &gt; nul
                        )

                        type target\parabank-cargo.log
                        exit /b 1
                    </value>
                                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                </entry>
                              </arguments>
                            </args>
                          </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                        </children>
                      </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTTreeStep>
                    </steps>
                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                </branches>
              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
                <name>Run Tests</name>
                <branches>
                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                    <name>default</name>
                    <steps>
                      <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTTreeStep>
                        <name>dir</name>
                        <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTSingleArgument">
                          <value class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue$GStringValue">
                            <value class="string">${env.PROJECT_DIR}</value>
                          </value>
                        </args>
                        <children>
                          <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                            <name>bat</name>
                            <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTNamedArgumentList">
                              <arguments class="linked-hash-map">
                                <entry>
                                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                    <key>script</key>
                                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                    <value class="string">mvn test &quot;-Dtest=LoginBlackBoxTest,ScenarioBasedTest&quot;</value>
                                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                </entry>
                              </arguments>
                            </args>
                          </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                          <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                            <name>bat</name>
                            <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTNamedArgumentList">
                              <arguments class="linked-hash-map">
                                <entry>
                                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                    <key>script</key>
                                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                    <value class="string">mvn &quot;%SERENITY_GOAL%:aggregate&quot;</value>
                                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                </entry>
                              </arguments>
                            </args>
                          </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                        </children>
                      </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTTreeStep>
                    </steps>
                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                </branches>
              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
            </stages>
            <uuid>f707583c-aef0-4c59-92d0-b5511a5ffac7</uuid>
          </stages>
          <postBuild>
            <conditions>
              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBuildCondition>
                <condition>always</condition>
                <branch>
                  <name>default</name>
                  <steps>
                    <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTTreeStep>
                      <name>dir</name>
                      <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTSingleArgument">
                        <value class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue$GStringValue">
                          <value class="string">${env.PROJECT_DIR}</value>
                        </value>
                      </args>
                      <children>
                        <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                          <name>bat</name>
                          <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTNamedArgumentList">
                            <arguments class="linked-hash-map">
                              <entry>
                                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                  <key>returnStatus</key>
                                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                  <value class="boolean">true</value>
                                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                              </entry>
                              <entry>
                                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                  <key>script</key>
                                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                  <value class="string">mvn &quot;%CARGO_GOAL%:stop&quot;</value>
                                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                              </entry>
                            </arguments>
                          </args>
                        </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                      </children>
                    </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTTreeStep>
                    <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                      <name>powershell</name>
                      <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTNamedArgumentList">
                        <arguments class="linked-hash-map">
                          <entry>
                            <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                              <key>script</key>
                            </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                            <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                              <value class="string">
                $ports = @(8080, 8205, 9001)
                foreach ($port in $ports) {
                    Get-NetTCPConnection -LocalPort $port -ErrorAction SilentlyContinue |
                        Select-Object -ExpandProperty OwningProcess -Unique |
                        ForEach-Object {
                            Stop-Process -Id $_ -Force -ErrorAction SilentlyContinue
                        }
                }
            </value>
                            </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                          </entry>
                        </arguments>
                      </args>
                    </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                    <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTTreeStep>
                      <name>dir</name>
                      <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTSingleArgument">
                        <value class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue$GStringValue">
                          <value class="string">${env.PROJECT_DIR}</value>
                        </value>
                      </args>
                      <children>
                        <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                          <name>junit</name>
                          <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTNamedArgumentList">
                            <arguments class="linked-hash-map">
                              <entry>
                                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                  <key>allowEmptyResults</key>
                                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                  <value class="boolean">true</value>
                                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                              </entry>
                              <entry>
                                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                  <key>testResults</key>
                                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                  <value class="string">target/surefire-reports/*.xml,target/failsafe-reports/*.xml</value>
                                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                              </entry>
                            </arguments>
                          </args>
                        </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                        <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                          <name>archiveArtifacts</name>
                          <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTNamedArgumentList">
                            <arguments class="linked-hash-map">
                              <entry>
                                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                  <key>allowEmptyArchive</key>
                                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                  <value class="boolean">true</value>
                                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                              </entry>
                              <entry>
                                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                  <key>artifacts</key>
                                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                  <value class="string">target/site/serenity/**,target/surefire-reports/**,target/failsafe-reports/**</value>
                                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                              </entry>
                            </arguments>
                          </args>
                        </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                      </children>
                    </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTTreeStep>
                  </steps>
                </branch>
              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBuildCondition>
            </conditions>
          </postBuild>
          <environment>
            <variables class="linked-hash-map">
              <entry>
                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                  <key>PROJECT_DIR</key>
                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                  <value class="string">D:\VVSS lab 5\parabank</value>
                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
              </entry>
              <entry>
                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                  <key>PARABANK_URL</key>
                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                  <value class="string">http://localhost:8080/parabank/index.htm</value>
                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
              </entry>
              <entry>
                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                  <key>MAVEN_OPTS</key>
                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                  <value class="string">-Djavax.net.ssl.trustStoreType=WINDOWS-ROOT</value>
                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
              </entry>
              <entry>
                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                  <key>CARGO_GOAL</key>
                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                  <value class="string">org.codehaus.cargo:cargo-maven3-plugin:1.10.27</value>
                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
              </entry>
              <entry>
                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                  <key>SERENITY_GOAL</key>
                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                  <value class="string">net.serenity-bdd.maven.plugins:serenity-maven-plugin:3.9.0</value>
                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
              </entry>
            </variables>
          </environment>
          <agent>
            <agentType>
              <key>any</key>
            </agentType>
          </agent>
          <options>
            <options>
              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTOption>
                <name>timestamps</name>
                <args/>
              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTOption>
              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTOption>
                <name>disableConcurrentBuilds</name>
                <args/>
              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTOption>
              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTOption>
                <name>timeout</name>
                <args>
                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKeyValueOrMethodCallPair>
                    <key>
                      <key>time</key>
                    </key>
                    <value class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue$ConstantValue">
                      <value class="int">20</value>
                    </value>
                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKeyValueOrMethodCallPair>
                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKeyValueOrMethodCallPair>
                    <key>
                      <key>unit</key>
                    </key>
                    <value class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue$ConstantValue">
                      <value class="string">MINUTES</value>
                    </value>
                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKeyValueOrMethodCallPair>
                </args>
              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTOption>
            </options>
            <inStage>false</inStage>
          </options>
        </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTPipelineDef>
      </pipelineDefs>
    </org.jenkinsci.plugins.pipeline.modeldefinition.actions.ExecutionModelAction>
    <org.jenkinsci.plugins.workflow.cps.EnvActionImpl plugin="workflow-cps@4331.v9d06ed4658ff">
      <env class="tree-map"/>
    </org.jenkinsci.plugins.workflow.cps.EnvActionImpl>
    <hudson.tasks.junit.TestResultAction plugin="junit@1403.vd9d1413fd205">
      <descriptions class="concurrent-hash-map"/>
      <failCount>0</failCount>
      <skipCount>0</skipCount>
      <totalCount>11</totalCount>
      <healthScaleFactor>1.0</healthScaleFactor>
      <testData/>
    </hudson.tasks.junit.TestResultAction>
    <jenkins.metrics.impl.SubTaskTimeInQueueAction plugin="metrics@4.2.37-494.v06f9a_939d33a_">
      <queuingDurationMillis>6</queuingDurationMillis>
      <blockedDurationMillis>0</blockedDurationMillis>
      <buildableDurationMillis>5</buildableDurationMillis>
      <waitingDurationMillis>0</waitingDurationMillis>
      <executingDurationMillis>133756</executingDurationMillis>
      <workUnitCount>1</workUnitCount>
    </jenkins.metrics.impl.SubTaskTimeInQueueAction>
  </actions>
  <queueId>32</queueId>
  <timestamp>1779193407828</timestamp>
  <startTime>1779193407835</startTime>
  <result>SUCCESS</result>
  <duration>134129</duration>
  <charset>UTF-8</charset>
  <keepLog>false</keepLog>
  <execution class="org.jenkinsci.plugins.workflow.cps.CpsFlowExecution">
    <result>SUCCESS</result>
    <script>pipeline {
    agent any

    options {
        timestamps()
        disableConcurrentBuilds()
        timeout(time: 20, unit: &apos;MINUTES&apos;)
    }

    environment {
        PROJECT_DIR = &apos;D:\\VVSS lab 5\\parabank&apos;
        PARABANK_URL = &apos;http://localhost:8080/parabank/index.htm&apos;
        MAVEN_OPTS = &apos;-Djavax.net.ssl.trustStoreType=WINDOWS-ROOT&apos;
        CARGO_GOAL = &apos;org.codehaus.cargo:cargo-maven3-plugin:1.10.27&apos;
        SERENITY_GOAL = &apos;net.serenity-bdd.maven.plugins:serenity-maven-plugin:3.9.0&apos;
    }

    stages {
        stage(&apos;Environment&apos;) {
            steps {
                bat &apos;java -version&apos;
                bat &apos;mvn -version&apos;
            }
        }

        stage(&apos;Build ParaBank&apos;) {
            steps {
                dir(env.PROJECT_DIR) {
                    bat &apos;mvn -DskipTests clean package&apos;
                }
            }
        }

        stage(&apos;Start ParaBank&apos;) {
            steps {
                dir(env.PROJECT_DIR) {
                    bat &apos;&apos;&apos;
                        @echo off
                        set JENKINS_NODE_COOKIE=dontKillMe
                        set BUILD_ID=dontKillMe
                        if exist target\\parabank-cargo.log del /q target\\parabank-cargo.log
                        start &quot;parabank&quot; /B cmd /c mvn -DskipTests &quot;%CARGO_GOAL%:run&quot; ^&gt; target\\parabank-cargo.log 2^&gt;^&amp;1
                    &apos;&apos;&apos;
                }
            }
        }

        stage(&apos;Wait For ParaBank&apos;) {
            steps {
                dir(env.PROJECT_DIR) {
                    bat &apos;&apos;&apos;
                        @echo off
                        for /L %%i in (1,1,40) do (
                            curl.exe --fail --silent &quot;%PARABANK_URL%&quot; | findstr /C:&quot;name=\\&quot;username\\&quot;&quot; &gt; nul
                            if not errorlevel 1 exit /b 0
                            echo ParaBank not ready yet, attempt %%i
                            ping 127.0.0.1 -n 4 &gt; nul
                        )

                        type target\\parabank-cargo.log
                        exit /b 1
                    &apos;&apos;&apos;
                }
            }
        }

        stage(&apos;Run Tests&apos;) {
            steps {
                dir(env.PROJECT_DIR) {
                    bat &apos;mvn test &quot;-Dtest=LoginBlackBoxTest,ScenarioBasedTest&quot;&apos;
                    bat &apos;mvn &quot;%SERENITY_GOAL%:aggregate&quot;&apos;
                }
            }
        }
    }

    post {
        always {
            dir(env.PROJECT_DIR) {
                bat returnStatus: true, script: &apos;mvn &quot;%CARGO_GOAL%:stop&quot;&apos;
            }

            powershell &apos;&apos;&apos;
                $ports = @(8080, 8205, 9001)
                foreach ($port in $ports) {
                    Get-NetTCPConnection -LocalPort $port -ErrorAction SilentlyContinue |
                        Select-Object -ExpandProperty OwningProcess -Unique |
                        ForEach-Object {
                            Stop-Process -Id $_ -Force -ErrorAction SilentlyContinue
                        }
                }
            &apos;&apos;&apos;

            dir(env.PROJECT_DIR) {
                junit allowEmptyResults: true, testResults: &apos;target/surefire-reports/*.xml,target/failsafe-reports/*.xml&apos;
                archiveArtifacts allowEmptyArchive: true, artifacts: &apos;target/site/serenity/**,target/surefire-reports/**,target/failsafe-reports/**&apos;
            }
        }
    }
}
</script>
    <loadedScripts class="linked-hash-map"/>
    <durabilityHint>MAX_SURVIVABILITY</durabilityHint>
    <timings class="map">
      <entry>
        <string>flowNode</string>
        <long>685074600</long>
      </entry>
      <entry>
        <string>classLoad</string>
        <long>195962000</long>
      </entry>
      <entry>
        <string>runQueue</string>
        <long>2926364300</long>
      </entry>
      <entry>
        <string>run</string>
        <long>9585277900</long>
      </entry>
      <entry>
        <string>parse</string>
        <long>46048400</long>
      </entry>
      <entry>
        <string>saveProgram</string>
        <long>6936536400</long>
      </entry>
    </timings>
    <internalCalls class="sorted-set">
      <string>hudson.model.Result.fromString</string>
      <string>org.jenkinsci.plugins.workflow.job.WorkflowRun.result</string>
    </internalCalls>
    <sandbox>true</sandbox>
    <iota>78</iota>
    <head>1:78</head>
    <done>true</done>
    <resumeBlocked>false</resumeBlocked>
    <storageDir>workflow-completed</storageDir>
  </execution>
  <completed>true</completed>
  <checkouts class="hudson.util.PersistedList"/>
</flow-build>