<?xml version='1.1' encoding='UTF-8'?>
<flow-build plugin="workflow-job@1571.1580.v18e46842c125">
  <actions>
    <hudson.model.CauseAction>
      <causeBag class="linked-hash-map">
        <entry>
          <hudson.model.Cause_-UserIdCause>
            <userId>admin</userId>
          </hudson.model.Cause_-UserIdCause>
          <int>1</int>
        </entry>
      </causeBag>
    </hudson.model.CauseAction>
    <jenkins.metrics.impl.TimeInQueueAction plugin="metrics@4.2.37-494.v06f9a_939d33a_">
      <queuingDurationMillis>1</queuingDurationMillis>
      <blockedDurationMillis>0</blockedDurationMillis>
      <buildableDurationMillis>0</buildableDurationMillis>
      <waitingDurationMillis>1</waitingDurationMillis>
    </jenkins.metrics.impl.TimeInQueueAction>
    <org.jenkinsci.plugins.workflow.libs.LibrariesAction plugin="pipeline-groovy-lib@797.v90ea_a_9b_e45a_0">
      <libraries/>
    </org.jenkinsci.plugins.workflow.libs.LibrariesAction>
    <org.jenkinsci.plugins.pipeline.modeldefinition.actions.ExecutionModelAction plugin="pipeline-model-definition@2.2277.v00573e73ddf1">
      <stagesUUID>823f8e63-902a-44b5-bce6-78fbd1e848d7</stagesUUID>
      <pipelineDefs>
        <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTPipelineDef plugin="pipeline-model-api@2.2277.v00573e73ddf1">
          <stages>
            <stages>
              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
                <name>Environment</name>
                <branches>
                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                    <name>default</name>
                    <steps>
                      <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTTreeStep>
                        <name>dir</name>
                        <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTSingleArgument">
                          <value class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue$ConstantValue">
                            <value class="string">parabank</value>
                          </value>
                        </args>
                        <children>
                          <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTScriptBlock>
                            <name>script</name>
                            <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTNamedArgumentList">
                              <arguments class="linked-hash-map">
                                <entry>
                                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                    <key>scriptBlock</key>
                                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                    <value class="string">if (isUnix()) {
                            sh &apos;java -version&apos;
                            sh &apos;mvn -version&apos;
                        } else {
                            bat &apos;java -version&apos;
                            bat &apos;mvn -version&apos;
                        }</value>
                                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                </entry>
                              </arguments>
                            </args>
                          </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTScriptBlock>
                        </children>
                      </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTTreeStep>
                    </steps>
                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                </branches>
              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
                <name>Clean Previous ParaBank</name>
                <branches>
                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                    <name>default</name>
                    <steps>
                      <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTTreeStep>
                        <name>dir</name>
                        <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTSingleArgument">
                          <value class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue$ConstantValue">
                            <value class="string">parabank</value>
                          </value>
                        </args>
                        <children>
                          <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTScriptBlock>
                            <name>script</name>
                            <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTNamedArgumentList">
                              <arguments class="linked-hash-map">
                                <entry>
                                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                    <key>scriptBlock</key>
                                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                    <value class="string">if (isUnix()) {
                            sh &apos;mvn &quot;$CARGO_GOAL:stop&quot; || true&apos;
                        } else {
                            bat returnStatus: true, script: &apos;mvn &quot;%CARGO_GOAL%:stop&quot;&apos;
                        }</value>
                                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                </entry>
                              </arguments>
                            </args>
                          </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTScriptBlock>
                        </children>
                      </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTTreeStep>
                    </steps>
                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                </branches>
              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
                <name>Start ParaBank</name>
                <branches>
                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                    <name>default</name>
                    <steps>
                      <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTTreeStep>
                        <name>dir</name>
                        <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTSingleArgument">
                          <value class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue$ConstantValue">
                            <value class="string">parabank</value>
                          </value>
                        </args>
                        <children>
                          <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTScriptBlock>
                            <name>script</name>
                            <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTNamedArgumentList">
                              <arguments class="linked-hash-map">
                                <entry>
                                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                    <key>scriptBlock</key>
                                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                    <value class="string">if (isUnix()) {
                            sh &apos;mvn -DskipTests package &quot;$CARGO_GOAL:start&quot;&apos;
                        } else {
                            bat &apos;mvn -DskipTests package &quot;%CARGO_GOAL%:start&quot;&apos;
                        }</value>
                                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                </entry>
                              </arguments>
                            </args>
                          </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTScriptBlock>
                        </children>
                      </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTTreeStep>
                    </steps>
                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                </branches>
              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
                <name>Warm Up ParaBank</name>
                <branches>
                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                    <name>default</name>
                    <steps>
                      <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTScriptBlock>
                        <name>script</name>
                        <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTNamedArgumentList">
                          <arguments class="linked-hash-map">
                            <entry>
                              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                <key>scriptBlock</key>
                              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                <value class="string">if (isUnix()) {
                        sh &apos;&apos;&apos;
                            for i in 1 2 3 4 5 6 7 8 9 10; do
                              curl --fail --silent --show-error &quot;$PARABANK_URL/index.htm&quot; &gt; /dev/null &amp;&amp; sleep 5 &amp;&amp; exit 0
                              sleep 3
                            done
                            exit 1
                        &apos;&apos;&apos;
                    } else {
                        powershell &apos;&apos;&apos;
                            $ErrorActionPreference = &apos;Stop&apos;
                            $ProgressPreference = &apos;SilentlyContinue&apos;
                            $ready = $false

                            for ($i = 1; $i -le 10; $i++) {
                                try {
                                    Write-Host &quot;Warm-up attempt $i&quot;
                                    Invoke-WebRequest -Uri &quot;$env:PARABANK_URL/index.htm&quot; -UseBasicParsing -TimeoutSec 5 | Out-Null
                                    Start-Sleep -Seconds 5
                                    $ready = $true
                                    break
                                } catch {
                                    Write-Host &quot;Warm-up not ready yet&quot;
                                    Start-Sleep -Seconds 3
                                }
                            }

                            if (-not $ready) {
                                throw &quot;ParaBank did not become ready in time.&quot;
                            }
                        &apos;&apos;&apos;
                    }</value>
                              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                            </entry>
                          </arguments>
                        </args>
                      </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTScriptBlock>
                    </steps>
                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                </branches>
              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
                <name>Run Serenity Tests</name>
                <branches>
                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                    <name>default</name>
                    <steps>
                      <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTTreeStep>
                        <name>dir</name>
                        <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTSingleArgument">
                          <value class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue$ConstantValue">
                            <value class="string">parabank</value>
                          </value>
                        </args>
                        <children>
                          <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTScriptBlock>
                            <name>script</name>
                            <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTNamedArgumentList">
                              <arguments class="linked-hash-map">
                                <entry>
                                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                    <key>scriptBlock</key>
                                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                    <value class="string">if (isUnix()) {
                            sh &apos;mvn test -Dtest=LoginBlackBoxTest,ScenarioBasedTest&apos;
                            sh &apos;mvn &quot;$SERENITY_GOAL:aggregate&quot;&apos;
                        } else {
                            bat &apos;mvn test &quot;-Dtest=LoginBlackBoxTest,ScenarioBasedTest&quot;&apos;
                            bat &apos;mvn &quot;%SERENITY_GOAL%:aggregate&quot;&apos;
                        }</value>
                                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                </entry>
                              </arguments>
                            </args>
                          </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTScriptBlock>
                        </children>
                      </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTTreeStep>
                    </steps>
                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                </branches>
              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
            </stages>
            <uuid>823f8e63-902a-44b5-bce6-78fbd1e848d7</uuid>
          </stages>
          <postBuild>
            <conditions>
              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBuildCondition>
                <condition>always</condition>
                <branch>
                  <name>default</name>
                  <steps>
                    <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTTreeStep>
                      <name>dir</name>
                      <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTSingleArgument">
                        <value class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue$ConstantValue">
                          <value class="string">parabank</value>
                        </value>
                      </args>
                      <children>
                        <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTScriptBlock>
                          <name>script</name>
                          <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTNamedArgumentList">
                            <arguments class="linked-hash-map">
                              <entry>
                                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                  <key>scriptBlock</key>
                                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                  <value class="string">if (isUnix()) {
                        sh &apos;mvn &quot;$CARGO_GOAL:stop&quot; || true&apos;
                    } else {
                        bat returnStatus: true, script: &apos;mvn &quot;%CARGO_GOAL%:stop&quot;&apos;
                    }</value>
                                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                              </entry>
                            </arguments>
                          </args>
                        </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTScriptBlock>
                      </children>
                    </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTTreeStep>
                    <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                      <name>junit</name>
                      <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTNamedArgumentList">
                        <arguments class="linked-hash-map">
                          <entry>
                            <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                              <key>allowEmptyResults</key>
                            </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                            <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                              <value class="boolean">true</value>
                            </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                          </entry>
                          <entry>
                            <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                              <key>testResults</key>
                            </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                            <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                              <value class="string">parabank/target/surefire-reports/*.xml,parabank/target/failsafe-reports/*.xml</value>
                            </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                          </entry>
                        </arguments>
                      </args>
                    </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                    <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                      <name>archiveArtifacts</name>
                      <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTNamedArgumentList">
                        <arguments class="linked-hash-map">
                          <entry>
                            <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                              <key>allowEmptyArchive</key>
                            </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                            <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                              <value class="boolean">true</value>
                            </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                          </entry>
                          <entry>
                            <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                              <key>artifacts</key>
                            </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                            <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                              <value class="string">parabank/target/site/serenity/**,parabank/target/surefire-reports/**,parabank/target/failsafe-reports/**</value>
                            </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                          </entry>
                        </arguments>
                      </args>
                    </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                  </steps>
                </branch>
              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBuildCondition>
            </conditions>
          </postBuild>
          <environment>
            <variables class="linked-hash-map">
              <entry>
                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                  <key>PARABANK_URL</key>
                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                  <value class="string">http://localhost:8080/parabank</value>
                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
              </entry>
              <entry>
                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                  <key>MAVEN_OPTS</key>
                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                  <value class="string">-Djavax.net.ssl.trustStoreType=WINDOWS-ROOT</value>
                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
              </entry>
              <entry>
                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                  <key>CARGO_GOAL</key>
                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                  <value class="string">org.codehaus.cargo:cargo-maven3-plugin:1.10.27</value>
                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
              </entry>
              <entry>
                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                  <key>SERENITY_GOAL</key>
                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                  <value class="string">net.serenity-bdd.maven.plugins:serenity-maven-plugin:3.9.0</value>
                </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
              </entry>
            </variables>
          </environment>
          <agent>
            <variables class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTClosureMap">
              <variables class="linked-hash-map">
                <entry>
                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                    <key>label</key>
                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                    <value class="string"></value>
                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                </entry>
                <entry>
                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                    <key>customWorkspace</key>
                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                    <value class="string">D:\VVSS lab 5</value>
                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                </entry>
              </variables>
            </variables>
            <agentType>
              <key>node</key>
            </agentType>
          </agent>
          <options>
            <options>
              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTOption>
                <name>timestamps</name>
                <args/>
              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTOption>
              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTOption>
                <name>disableConcurrentBuilds</name>
                <args/>
              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTOption>
              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTOption>
                <name>timeout</name>
                <args>
                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKeyValueOrMethodCallPair>
                    <key>
                      <key>time</key>
                    </key>
                    <value class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue$ConstantValue">
                      <value class="int">20</value>
                    </value>
                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKeyValueOrMethodCallPair>
                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKeyValueOrMethodCallPair>
                    <key>
                      <key>unit</key>
                    </key>
                    <value class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue$ConstantValue">
                      <value class="string">MINUTES</value>
                    </value>
                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKeyValueOrMethodCallPair>
                </args>
              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTOption>
            </options>
            <inStage>false</inStage>
          </options>
        </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTPipelineDef>
      </pipelineDefs>
    </org.jenkinsci.plugins.pipeline.modeldefinition.actions.ExecutionModelAction>
    <hudson.tasks.junit.TestResultAction plugin="junit@1403.vd9d1413fd205">
      <descriptions class="concurrent-hash-map"/>
      <failCount>3</failCount>
      <skipCount>0</skipCount>
      <totalCount>247</totalCount>
      <healthScaleFactor>1.0</healthScaleFactor>
      <testData/>
    </hudson.tasks.junit.TestResultAction>
    <jenkins.metrics.impl.SubTaskTimeInQueueAction plugin="metrics@4.2.37-494.v06f9a_939d33a_">
      <queuingDurationMillis>5</queuingDurationMillis>
      <blockedDurationMillis>0</blockedDurationMillis>
      <buildableDurationMillis>4</buildableDurationMillis>
      <waitingDurationMillis>0</waitingDurationMillis>
      <executingDurationMillis>1238874</executingDurationMillis>
      <workUnitCount>1</workUnitCount>
    </jenkins.metrics.impl.SubTaskTimeInQueueAction>
    <jenkins.model.InterruptedBuildAction>
      <causes>
        <org.jenkinsci.plugins.workflow.steps.TimeoutStepExecution_-ExceededTimeout plugin="workflow-basic-steps@1098.v808b_fd7f8cf4">
          <nodeId>11</nodeId>
        </org.jenkinsci.plugins.workflow.steps.TimeoutStepExecution_-ExceededTimeout>
      </causes>
    </jenkins.model.InterruptedBuildAction>
  </actions>
  <queueId>24</queueId>
  <timestamp>1779188385762</timestamp>
  <startTime>1779188385772</startTime>
  <result>ABORTED</result>
  <duration>1239220</duration>
  <charset>UTF-8</charset>
  <keepLog>false</keepLog>
  <execution class="org.jenkinsci.plugins.workflow.cps.CpsFlowExecution">
    <result>ABORTED</result>
    <script>pipeline {
    agent {
        node {
            label &apos;&apos;
            customWorkspace &apos;D:\\VVSS lab 5&apos;
        }
    }

    options {
        timestamps()
        disableConcurrentBuilds()
        timeout(time: 20, unit: &apos;MINUTES&apos;)
    }

    environment {
        PARABANK_URL = &apos;http://localhost:8080/parabank&apos;
        MAVEN_OPTS = &apos;-Djavax.net.ssl.trustStoreType=WINDOWS-ROOT&apos;
        CARGO_GOAL = &apos;org.codehaus.cargo:cargo-maven3-plugin:1.10.27&apos;
        SERENITY_GOAL = &apos;net.serenity-bdd.maven.plugins:serenity-maven-plugin:3.9.0&apos;
    }

    stages {
        stage(&apos;Environment&apos;) {
            steps {
                dir(&apos;parabank&apos;) {
                    script {
                        if (isUnix()) {
                            sh &apos;java -version&apos;
                            sh &apos;mvn -version&apos;
                        } else {
                            bat &apos;java -version&apos;
                            bat &apos;mvn -version&apos;
                        }
                    }
                }
            }
        }

        stage(&apos;Clean Previous ParaBank&apos;) {
            steps {
                dir(&apos;parabank&apos;) {
                    script {
                        if (isUnix()) {
                            sh &apos;mvn &quot;$CARGO_GOAL:stop&quot; || true&apos;
                        } else {
                            bat returnStatus: true, script: &apos;mvn &quot;%CARGO_GOAL%:stop&quot;&apos;
                        }
                    }
                }
            }
        }

        stage(&apos;Start ParaBank&apos;) {
            steps {
                dir(&apos;parabank&apos;) {
                    script {
                        if (isUnix()) {
                            sh &apos;mvn -DskipTests package &quot;$CARGO_GOAL:start&quot;&apos;
                        } else {
                            bat &apos;mvn -DskipTests package &quot;%CARGO_GOAL%:start&quot;&apos;
                        }
                    }
                }
            }
        }

        stage(&apos;Warm Up ParaBank&apos;) {
            steps {
                script {
                    if (isUnix()) {
                        sh &apos;&apos;&apos;
                            for i in 1 2 3 4 5 6 7 8 9 10; do
                              curl --fail --silent --show-error &quot;$PARABANK_URL/index.htm&quot; &gt; /dev/null &amp;&amp; sleep 5 &amp;&amp; exit 0
                              sleep 3
                            done
                            exit 1
                        &apos;&apos;&apos;
                    } else {
                        powershell &apos;&apos;&apos;
                            $ErrorActionPreference = &apos;Stop&apos;
                            $ProgressPreference = &apos;SilentlyContinue&apos;
                            $ready = $false

                            for ($i = 1; $i -le 10; $i++) {
                                try {
                                    Write-Host &quot;Warm-up attempt $i&quot;
                                    Invoke-WebRequest -Uri &quot;$env:PARABANK_URL/index.htm&quot; -UseBasicParsing -TimeoutSec 5 | Out-Null
                                    Start-Sleep -Seconds 5
                                    $ready = $true
                                    break
                                } catch {
                                    Write-Host &quot;Warm-up not ready yet&quot;
                                    Start-Sleep -Seconds 3
                                }
                            }

                            if (-not $ready) {
                                throw &quot;ParaBank did not become ready in time.&quot;
                            }
                        &apos;&apos;&apos;
                    }
                }
            }
        }

        stage(&apos;Run Serenity Tests&apos;) {
            steps {
                dir(&apos;parabank&apos;) {
                    script {
                        if (isUnix()) {
                            sh &apos;mvn test -Dtest=LoginBlackBoxTest,ScenarioBasedTest&apos;
                            sh &apos;mvn &quot;$SERENITY_GOAL:aggregate&quot;&apos;
                        } else {
                            bat &apos;mvn test &quot;-Dtest=LoginBlackBoxTest,ScenarioBasedTest&quot;&apos;
                            bat &apos;mvn &quot;%SERENITY_GOAL%:aggregate&quot;&apos;
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            dir(&apos;parabank&apos;) {
                script {
                    if (isUnix()) {
                        sh &apos;mvn &quot;$CARGO_GOAL:stop&quot; || true&apos;
                    } else {
                        bat returnStatus: true, script: &apos;mvn &quot;%CARGO_GOAL%:stop&quot;&apos;
                    }
                }
            }
            junit allowEmptyResults: true, testResults: &apos;parabank/target/surefire-reports/*.xml,parabank/target/failsafe-reports/*.xml&apos;
            archiveArtifacts allowEmptyArchive: true, artifacts: &apos;parabank/target/site/serenity/**,parabank/target/surefire-reports/**,parabank/target/failsafe-reports/**&apos;
        }
    }
}
</script>
    <loadedScripts class="linked-hash-map"/>
    <durabilityHint>MAX_SURVIVABILITY</durabilityHint>
    <timings class="map">
      <entry>
        <string>flowNode</string>
        <long>901791100</long>
      </entry>
      <entry>
        <string>classLoad</string>
        <long>113567900</long>
      </entry>
      <entry>
        <string>runQueue</string>
        <long>3524413400</long>
      </entry>
      <entry>
        <string>run</string>
        <long>3589652000</long>
      </entry>
      <entry>
        <string>parse</string>
        <long>39954100</long>
      </entry>
      <entry>
        <string>saveProgram</string>
        <long>1635529500</long>
      </entry>
    </timings>
    <internalCalls class="sorted-set">
      <string>hudson.model.Result.fromString</string>
      <string>org.jenkinsci.plugins.pipeline.StageStatus.TAG_NAME</string>
      <string>org.jenkinsci.plugins.workflow.job.WorkflowRun.result</string>
    </internalCalls>
    <sandbox>true</sandbox>
    <iota>97</iota>
    <head>1:97</head>
    <done>true</done>
    <resumeBlocked>false</resumeBlocked>
    <storageDir>workflow-completed</storageDir>
  </execution>
  <completed>true</completed>
  <checkouts class="hudson.util.PersistedList"/>
</flow-build>